# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbrjvFwjwbHrFh53dKmf2ViCBTB28U4E

1. Take your roll number. Extract its individual digits, and multiply each digit by 10 to form your list L (10 numbers in list now). i. ii. Print L Add two numbers of your choice to L — one using append() and one using insert() at a specific position. Print L after each and explain in a comment what changed. iii. Remove two elements from L — one using remove() and one using pop(). Print L after each. iv. Sort L in ascending order using sort(), then descending order using sort(reverse=True). Print both. v. Use slicing to print the first three elements and the last three elements of L in a single line each. vi. Use list comprehension to create a new list containing only the elements of L that are greater than the average of L.

### Task 1: Create List L from a Roll Number
"""

# Assuming a sample roll number (e.g., 1234567890). Please replace with your actual roll number.
roll_number = "1024170393"

# Extract individual digits and multiply each by 10 to form list L
L = [int(digit) * 10 for digit in roll_number]

# Print L
print("Initial list L:", L)

"""### Task 2: Add Elements to L using `append()` and `insert()`"""

# Add a number using append()
L.append(100)
print("List L after append(100):")
print(L)
# Explanation: The number 100 was added to the end of the list L.

# Add a number using insert() at a specific position (e.g., index 2)
L.insert(2, 25)
print("\nList L after insert(2, 25):")
print(L)
# Explanation: The number 25 was inserted at index 2 (the third position) in list L.
# Elements originally at index 2 and beyond were shifted to the right.

"""### Task 3: Remove Elements from L using `remove()` and `pop()`"""

# Remove an element using remove() (e.g., remove the first occurrence of 20)
if 20 in L:
    L.remove(20)
    print("List L after remove(20):")
    print(L)
else:
    print("20 not found in list for removal using remove(). Current list L:", L)

# Remove an element using pop() (e.g., remove the element at index 0)
if len(L) > 0:
    popped_element = L.pop(0)
    print(f"\nList L after pop(0) (removed element: {popped_element}):")
    print(L)
else:
    print("List is empty, cannot perform pop(0). Current list L:", L)

"""### Task 4: Sort List L"""

# Sort L in ascending order
L.sort()
print("List L after sorting in ascending order:")
print(L)

# Sort L in descending order
L.sort(reverse=True)
print("\nList L after sorting in descending order:")
print(L)

"""### Task 5: Use Slicing on L"""

# Print the first three elements of L
print("First three elements of L:", L[:3])

# Print the last three elements of L
print("Last three elements of L:", L[-3:])

"""### Task 6: List Comprehension for Elements Greater Than Average"""

# Calculate the average of L
if len(L) > 0:
    average_L = sum(L) / len(L)
    print(f"Average of L: {average_L:.2f}")

    # Create a new list containing only elements greater than the average of L
    L_greater_than_average = [x for x in L if x > average_L]
    print("List L with elements greater than average:", L_greater_than_average)
else:
    print("List L is empty, cannot calculate average or filter elements.")

"""### Task 2.i: Create Tuple `scores`, Find Highest/Lowest Score"""

# Create a tuple named scores using the first 8 values from list L
scores = tuple(L[:8])
print("Tuple scores:", scores)

# Find the highest score and its index
highest_score = max(scores)
highest_score_index = scores.index(highest_score)
print(f"Highest score: {highest_score} (at index {highest_score_index})")

# Find the lowest score and how many times it appears
lowest_score = min(scores)
lowest_score_count = scores.count(lowest_score)
print(f"Lowest score: {lowest_score} (appears {lowest_score_count} time(s))")

"""### Task 2.ii: Reverse the Tuple and Return as a List"""

# Reverse the tuple and return the result as a list
reversed_scores_list = list(reversed(scores))
print("Reversed scores as a list:", reversed_scores_list)
# Tuples cannot be reversed in place because they are immutable; their elements cannot be changed after creation.

"""### Task 2.iii: Ask User for Input Score and Find Index"""

# Ask the user to input a score
# For demonstration, we'll use a fixed value or you can uncomment input()
# user_score_str = input("Please enter a score to search for: ")
# user_score = int(user_score_str)
user_score = 30 # Example input
print(f"Searching for score: {user_score}")

# Print its first occurrence index if present, or a not present message
if user_score in scores:
    index_of_score = scores.index(user_score)
    print(f"The score {user_score} is found at index: {index_of_score}")
else:
    print(f"The score {user_score} is not present in the tuple.")

"""### Task 2.iv: Attempt to Change an Element of the Tuple"""

# Attempt to change one element of the tuple directly (e.g., scores[0] = 100)
try:
    scores[0] = 100
except TypeError as e:
    print(f"Error: {e}")
# This happens because tuples are immutable, meaning their contents cannot be modified after creation, unlike lists which are mutable.

"""### Task 2.v: Unpack the Tuple"""

# Unpack the tuple into a first score, a second score, and all remaining scores
first_score, second_score, *remaining_scores = scores

print(f"First score: {first_score}")
print(f"Second score: {second_score}")
print(f"Remaining scores: {remaining_scores}")

"""### Task 3.i: Set Random Seed and Generate List of Random Numbers"""

import random

# Set the random seed to your roll number for reproducibility
# The roll_number variable is available from previous cells.
random.seed(int(roll_number))
print(f"Random seed set to: {roll_number}")

# Generate a list of 100 random numbers between 100 and 900 (inclusive)
random_numbers_list = [random.randint(100, 900) for _ in range(100)]
print("Generated list of 100 random numbers (first 10 elements):", random_numbers_list[:10])

"""### Task 3.ii & 3.iii: Count Odd and Even Numbers"""

# Count and print all odd numbers in the list
odd_numbers_count = sum(1 for num in random_numbers_list if num % 2 != 0)
print(f"Total odd numbers in the list: {odd_numbers_count}")

# Count and print all even numbers in the list
even_numbers_count = sum(1 for num in random_numbers_list if num % 2 == 0)
print(f"Total even numbers in the list: {even_numbers_count}")

"""### Task 3.iv: Count and List Prime Numbers"""

def is_prime(num):
    if num < 2: # Numbers less than 2 are not prime
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Count and print all prime numbers in the list
prime_numbers_list = [num for num in random_numbers_list if is_prime(num)]
prime_numbers_count = len(prime_numbers_list)

print(f"Total prime numbers in the list: {prime_numbers_count}")
print("Actual list of prime numbers found:", prime_numbers_list)

"""### Task 3.v: Find the Most Frequent Number"""

from collections import Counter

# Find the number that occurs most frequently and its count
# Counter returns a dictionary-like object where keys are elements and values are their counts.
# most_common(1) returns a list of the n most common elements and their counts, as tuples.
most_common_number = Counter(random_numbers_list).most_common(1)

if most_common_number:
    number, count = most_common_number[0]
    print(f"The most frequent number is: {number}")
    print(f"It occurs {count} time(s).")
else:
    print("The list is empty, cannot determine the most frequent number.")

"""### Task 4: Set Operations"""

# Using the same 8 digits of your roll number from Q1 (before multiplying by 10)
# Extract first 8 individual digits from the roll_number string
roll_digits = [int(digit) for digit in roll_number[:8]]

# Create set A = {digit × 7 for each digit}
A = {digit * 7 for digit in roll_digits}
print("Set A:", A)

# Create set B = {digit × 9 for each digit}
B = {digit * 9 for digit in roll_digits}
print("Set B:", B)

"""### Task 4.vi: Find the Union of A and B"""

# Find the union of A and B — all unique values across both sets
union_AB = A.union(B)
print("Union of A and B (A | B):", union_AB)

"""### Task 4.vii: Find the Intersection of A and B"""

# Find the intersection of A and B — values common to both
intersection_AB = A.intersection(B)
print("Intersection of A and B (A & B):", intersection_AB)

"""### Task 4.viii: Find A - B and B - A using `difference()`"""

# Find A - B
difference_A_B = A.difference(B)
print("Difference A - B (A - B):", difference_A_B)

# Find B - A
difference_B_A = B.difference(A)
print("Difference B - A (B - A):", difference_B_A)
# The difference() method returns elements present in the first set but not in the second, while symmetric_difference() returns elements present in either set, but not in both.

"""### Task 4.ix: Find the Symmetric Difference of A and B"""

# Find the symmetric difference of A and B
symmetric_difference_AB = A.symmetric_difference(B)
print("Symmetric Difference of A and B (A ^ B):", symmetric_difference_AB)

"""### Task 4.x: Check Subset and Superset Relationships"""

# Check whether A is a subset of B
is_A_subset_B = A.issubset(B)
print(f"Is A a subset of B? {is_A_subset_B}")

# Check whether B is a superset of A
is_B_superset_A = B.issuperset(A)
print(f"Is B a superset of A? {is_B_superset_A}")

"""### Task 4.xi: Remove X from Set A using `discard()`"""

# Ask the user to input a value X
# For demonstration, we'll use a fixed value or you can uncomment input()
# user_value_X_str = input("Please enter a value X to remove from set A: ")
# user_value_X = int(user_value_X_str)
user_value_X = 7 # Example input: a value that might be in A

print(f"Attempting to discard {user_value_X} from Set A...")
A.discard(user_value_X)
print("Set A after discard():", A)

# Let's try to discard a value not in the set, to show it doesn't raise an error
user_value_X_not_in_A = 999
print(f"Attempting to discard {user_value_X_not_in_A} from Set A...")
A.discard(user_value_X_not_in_A)
print("Set A after discarding a non-existent value:", A)

# discard() is safer than remove() because it does not raise a KeyError if the element is not found in the set, allowing the program to continue without interruption.

"""### Task 5: Dictionary Operations"""

# Initial dictionary
my_dict = {
    "name": "Jane Doe",
    "roll_no": roll_number,
    "branch": "Computer Science",
    "age": 20,
    "city": "New York"
}
print("Original Dictionary:\n", my_dict)

"""### Task 5.i: Rename 'city' to 'location'"""

# Rename the key “city” to “location” using dictionary comprehension
# This creates a new dictionary with the renamed key
my_dict = {("location" if k == "city" else k): v for k, v in my_dict.items()}
print("\nDictionary after renaming 'city' to 'location':\n", my_dict)

"""### Task 5.ii: Add 'cgpa' Key"""

# Add a new key “cgpa” with your CGPA as its value
my_dict["cgpa"] = 8.5
print("\nDictionary after adding 'cgpa':\n", my_dict)

"""### Task 5.iii: Update 'age' Value"""

# Update the value of “age” by increasing it by 1
my_dict["age"] += 1
print("\nDictionary after updating 'age':\n", my_dict)

"""### Task 5.iv: Delete 'branch' using `pop()` and `del`"""

# Create a copy of the dictionary for pop()
my_dict_copy_pop = my_dict.copy()
removed_branch_pop = my_dict_copy_pop.pop("branch")
print("\nDictionary after deleting 'branch' with pop():\n", my_dict_copy_pop)
print(f"Value removed by pop(): {removed_branch_pop}")

# Create another copy of the dictionary for del
my_dict_copy_del = my_dict.copy()
del my_dict_copy_del["branch"]
print("\nDictionary after deleting 'branch' with del:\n", my_dict_copy_del)

# Explanation of difference:
# pop() removes the key-value pair and returns the value, while del simply removes the key-value pair without returning anything.

"""### Task 5.v: Iterate and Print Key-Value Pairs"""

# Iterate over the dictionary using .items() and print each key-value pair
print("\nIterating through the dictionary:")
for key, value in my_dict.items():
    print(f"{key} -> {value}")

"""### Task 5.vi: Check for Non-Existent Key ('email')"""

# Check for existence of 'email' and print a fallback message
if "email" in my_dict:
    print(f"\nEmail: {my_dict['email']}")
else:
    print("\n'email' key not found. Providing safe fallback message: Email address not available.")

"""### Task 5.vii: Merge Dictionaries with `**dict1, **dict2`"""

# Create a second dictionary friend_dict
friend_dict = {
    "name": "John Doe",
    "roll_no": "9876543210",
    "branch": "Electrical Engineering",
    "age": 21,
    "city": "Los Angeles"
}
print("\nFriend's Dictionary:\n", friend_dict)

# Merge it with your own using the {**dict1, **dict2} syntax
merged_dict = {**my_dict, **friend_dict}
print("\nMerged Dictionary (friend_dict overwrites my_dict where keys overlap):\n", merged_dict)

# Explanation:
# When merging dictionaries using {**dict1, **dict2}, values from the second dictionary (friend_dict in this case) 'win' for any shared keys, overwriting the values from the first dictionary (my_dict).

"""### Task 5.viii: Dictionary Comprehension for String Values"""

# Use dictionary comprehension to create a new dictionary with only string values
string_values_dict = {k: v for k, v in my_dict.items() if isinstance(v, str)}
print("\nNew Dictionary with only string values from my_dict:\n", string_values_dict)